### ISSUE TITLE
Quartz causes 120 to 1500 connection attempts per second when DB is not available

### ISSUE THREAD

**Issue by oberlies** [quartz-scheduler/quartz#71]
When an JobPersistenceException is caught in the main QuartzSchedulerThread loop, the loop continues and immediately retries to read the triggers from the database. This leads to 120 to 1500 database connection attempts per second (!!). This leads to a flood of error log entries on our server.

Quartz should automatically throttle the retry attempts in case of database connection errors.

The first exception (and only one logged by Quartz directly) is

```
2015 10 10 18:58:06#+00#ERROR#org.quartz.core.ErrorLogger##anonymous#global_QuartzSchedulerThread#na#services#dispatcher#web##An error occurred while scanning for the next triggers to fire.
org.quartz.JobPersistenceException: Failed to obtain DB connection from data source 'DefaultDB': java.sql.SQLException: Could not retrieve datasource via JNDI url 'java:comp/env/jdbc/DefaultDB' <exception details from driver>. [See nested exception: java.sql.SQLException: Could not retrieve datasource via JNDI url 'java:comp/env/jdbc/DefaultDB' <exception details from driver>.]
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:778)
    at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3784)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2756)
    at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)
Caused by: java.sql.SQLException: Could not retrieve datasource via JNDI url 'java:comp/env/jdbc/DefaultDB' <exception details from driver>.
    at org.quartz.utils.JNDIConnectionProvider.getConnection(JNDIConnectionProvider.java:163)
    at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:775)
    ... 4 more|
```

---

This issue was originally reported and discussed here: https://jira.terracotta.org/jira/browse/QTZ-491

**Comment by zemian** [comment]
Hi @oberlies , have you tried increasing "org.quartz.scheduler.dbFailureRetryInterval" value?

**Comment by seancarroll** [comment]
I'm using the default value of 15000 for org.quartz.scheduler.dbFailureRetryInterval and the number of attempts does not appear to correlate to that value

**Comment by mag01** [comment]
It's a longstanding issue that's been plaguing us form time to time as well.
There's a loop that unfortunately doesn't take any retry interval into account at all, it just keeps retrying over and over again without any period of suspension.
See also the following old thread http://forums.terracotta.org/forums/posts/list/8929.page

**Comment by jhouserizer** [comment]
Thought: Perhaps within the connection provider(s) we could track the failure to get an underlying connection and add a delay for retries there, thus ensuring the interval is applied everywhere?

**Comment by jhouserizer** [comment]
#116 should help with this issue, though worker threads trying to mark jobs complete will still be "noisy".

**Comment by ddekany** [comment]
This is a major issue as it endangers the stability of services by filling the disk partition when a DB outage occurs. It was originally reported on 26/Oct/15.

**Comment by zemian** [comment]
Is issue is already resolved with the PR #116. The changes has already gone in the 2.3.0 release. Will close this.

**Comment by mujahidmasood** [comment]
I could not find these changes in 2.3.0 as well in 2.3.1

**Comment by mujahidmasood** [comment]
> Is issue is already resolved with the PR #116. The changes has already gone in the 2.3.0 release. Will close this.

Unfortunately, I could not find the changes in version 2.3.0 or 2.3.1!
Its still failing
